// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-cytqCDs1StCXWI1PgIkk4oCSO8kVE4',
    appId: '1:100960866797:web:8d98d61b10e39f456457e4',
    messagingSenderId: '100960866797',
    projectId: 'mother-and-baby-smartcare-app',
    authDomain: 'mother-and-baby-smartcare-app.firebaseapp.com',
    storageBucket: 'mother-and-baby-smartcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAULqaZV3MgrIKYCwvjesecxq_MbIbo894',
    appId: '1:100960866797:android:a26c23acc82da4b46457e4',
    messagingSenderId: '100960866797',
    projectId: 'mother-and-baby-smartcare-app',
    storageBucket: 'mother-and-baby-smartcare-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWWrgRKCd6SN-Kuak5dXyts2SnV2zAhOc',
    appId: '1:100960866797:ios:0b2f059715a424dc6457e4',
    messagingSenderId: '100960866797',
    projectId: 'mother-and-baby-smartcare-app',
    storageBucket: 'mother-and-baby-smartcare-app.firebasestorage.app',
    androidClientId: '100960866797-76ncompbtth1gj8a67jdv3ubfdf1f8u7.apps.googleusercontent.com',
    iosClientId: '100960866797-7fvdp314td6l38qikvn4cnl6nn7b1e7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.motherAndBabySmartcare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWWrgRKCd6SN-Kuak5dXyts2SnV2zAhOc',
    appId: '1:100960866797:ios:0b2f059715a424dc6457e4',
    messagingSenderId: '100960866797',
    projectId: 'mother-and-baby-smartcare-app',
    storageBucket: 'mother-and-baby-smartcare-app.firebasestorage.app',
    androidClientId: '100960866797-76ncompbtth1gj8a67jdv3ubfdf1f8u7.apps.googleusercontent.com',
    iosClientId: '100960866797-7fvdp314td6l38qikvn4cnl6nn7b1e7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.motherAndBabySmartcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-cytqCDs1StCXWI1PgIkk4oCSO8kVE4',
    appId: '1:100960866797:web:0afd431f0a8722306457e4',
    messagingSenderId: '100960866797',
    projectId: 'mother-and-baby-smartcare-app',
    authDomain: 'mother-and-baby-smartcare-app.firebaseapp.com',
    storageBucket: 'mother-and-baby-smartcare-app.firebasestorage.app',
  );
}
